#!/bin/bash

# Display active Internet and UNIX domain listening sockets with PID/Program name
echo "Active Internet connections (only servers)"
sudo ss -tulnp | awk 'NR==1 || /LISTEN/'

echo "Active UNIX domain sockets (only servers)"
sudo ss -xlnp | awk 'NR==1 || /LISTEN/'

